### PR TITLE
Support 1.6.14

### PR DESCRIPTION
**Pull request by beef331**
Tests pass on 1.6.14 so not much reason not to support it for the time being. Please do make a git tag :smile:

### CODE REVIEW

**Comment by termermc** [comment]
Docs won't generate on 1.6.14 unless uses of `addr` are replaced with `unsafeAddr`. Isn't that feature deprecated?

**Comment by beef331** [comment]
Ugh more work is required, seemed so easy to add 1.6.14 support.

**Comment by termermc** [comment]
If it's not a deprecated feature, `unsafeAddr` can be used in place of `addr`. If it is, a few `when` blocks can be used. It's not a big set of changes, and everything still passes on my testing with `unsafeAddr`.

**Comment by termermc** [comment]
Oh yeah, looks like it was deprecated: https://github.com/nim-lang/RFCs/issues/369
So `when` can be added to the code and `runnableExamples` blocks without issue.

**Comment by beef331** [comment]
Yea I knew how to fix it of course, I just didnt want to have to go through and do it :stuck_out_tongue:

**Comment by termermc** [comment]
The only things that need to be updated now are the README to remove the inaccurate bit about 2.0.0 support, and `runnableExamples`, the latter of which could have comments explaining `unsafeAddr` being required pre-2.0.0

**Pull request merged**
